# Generated by Django 2.2.4 on 2019-08-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=255, verbose_name='Nome Responsável')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('str_cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('str_numero', models.CharField(max_length=5, verbose_name='Número Res.')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('horario_funcionamento', models.TextField()),
                ('observacao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
