# Generated by Django 2.2.4 on 2019-08-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_ong'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='email',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='E-mail'),
        ),
    ]
